### ISSUE TITLE
What's left to do?

### ISSUE THREAD

**Issue by bas-ie** [johnstonbl01/clementinejs-fcc#1]
Congratulations on a well-put-together project. I just did a quick trial install on Cloud 9, it likes `libkrb5-dev` for Passport and it needs to be told to start `mongod` and use port 8080 but other than that, it was pretty smooth. Are there any outstanding tasks you wish people would work on in order to get it ready for wider use?

Edit: note, this was with Node 4.0.0, installed via `nvm`.

**Comment by johnstonbl01** [comment]
Thanks for that. I should have everything wrapped up by Saturday. Only thing left is to finish up a few documentation changes, and I'm updating some of the styling for the docs. Does C9 require use of port 8080? If so, I can change the default port.

At this point, it's just a few things on my side to get finished up, which I expect to be done on Saturday. I could use some support on updating some of the docs for deployment to C9, though. That'd be helpful.

**Comment by bas-ie** [comment]
That's great news. I'd be happy to help with documentation, I've been using C9 for another project recently.

C9 forwards port 8080 to 80, and I believe 8081 and 8082 are also available. Other ports won't be visible outside the container, so typically they define `$PORT` to 8080 by default and use something like:

```
server.listen(process.env.PORT || 3000, process.env.IP || "0.0.0.0", function(){
  var addr = server.address();
  console.log("Server listening at", addr.address + ":" + addr.port);
});
```

**Comment by johnstonbl01** [comment]
Awesome - I appreciate the help. Could you add a section to the FCC docs about deploying to c9? That would be wonderful! I know that typical apps store the environmental settings like port in additional Node modules, but for the sake of simplicity I'd like to just keep it inside the `server.js` file.

I'll also make these changes:
- Add a note to the standard version document about the port for c9.
- Update the default port of the FCC version to be 8080 instead of 3000

**Comment by johnstonbl01** [comment]
@richchurcher : Here's where I'm at - 
- Updated FCC version to use port 8080. It's been pushed to GH.
- Updated docs have been pushed as well. It's a pretty significant change to the look / feel.

Any update on when you can create a section about deploying to C9?

**Comment by johnstonbl01** [comment]
Added this to docs over the weekend.
