### ISSUE TITLE
Clementine.js Passport Authentication Tutorial

### ISSUE THREAD

**Issue by holmberd** [johnstonbl01/clementinejs-fcc#15]
In the tutorial http://www.clementinejs.com/tutorials/tutorial-passport.html the port is switched from 3000 to 8080, which is mentioned at the top of the tutorial. It would be nice for clarification to put in a note that **clickController.client.js** apiUrl needs to be changed accordingly, i.e: 
`var apiUrl = 'http://localhost:3000/api/clicks';` 
`var apiUrl = 'http://localhost:8080/api/clicks';`

Other than that small note it was a good tutorial, thanks.

**Comment by johnstonbl01** [comment]
Seems reasonable. Would you like to open a PR to address that issue?

**Comment by holmberd** [comment]
I think a PR here will only add to the confusion of those who didn't follow the tutorial from part 1, but instead cloned the clementinejs-fcc. The fcc rep were in closest relation to the [passport tutorial](http://www.clementinejs.com/tutorials/tutorial-passport.html) so I mentioned it here instead.

**Comment by johnstonbl01** [comment]
I was thinking a PR to add the note for clarification you mentioned in the comment above? All the documentation is in the `gh-pages` branch of the clementine.js repo. If this is something you're interested in doing, let me know.

**Comment by holmberd** [comment]
@johnstonbl01 I found the docs and opened a PR (Fix #15) in the repo.

**Comment by johnstonbl01** [comment]
Did you delete the PR? Not seeing it out there any longer.

**Comment by holmberd** [comment]
Sorry, it is there now: https://github.com/johnstonbl01/clementinejs/pull/68

**Comment by johnstonbl01** [comment]
Addressed in PR.
