### ISSUE TITLE
Mongoose Deprecation Warning

### ISSUE THREAD

**Issue by MiloATH** [johnstonbl01/clementinejs-fcc#17]
When running the server, the following warning appears.

> (node:18225) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client

This is talked about on the mongoose repo here: Automattic/mongoose#5399

**Comment by whackdev** [comment]
I fixed this by adding the `{ useMongoClient: true }` argument in the `mongoose.connect(process.env.MONGO_URI)` on line 13 of server.js
