### ISSUE TITLE
Forgotten step

### ISSUE THREAD

**Issue by tylerthehaas** [johnstonbl01/clementinejs-fcc#2]
In order for the app to work you must create an app.use() statement in server.js and that is not covered in the fcc tutorial.  Please update.  Thanks for all your hard work on this.  It has been very beneficial.

**Comment by johnstonbl01** [comment]
Fixed. Can be found in [this section](http://johnstonbl01.github.io/clementinejs/tutorials/tutorial-passport.html#RefactorCommonAJAXFunctions) of the tutorial.
