### ISSUE TITLE
clementinejs-fcc running on heroku

### ISSUE THREAD

**Issue by TheHexorcist** [johnstonbl01/clementinejs-fcc#7]
I've run into a problem with mongoose.  Apparently it currently doesn't support Mongodb 3.0.  when I loaded clementine to heroku it requires a setup of the Mongolab add-in.  Mongolab is supporting only 3.0.  When you login using the mongo you will get an authentication error because its gone to a SCRAM-SHA-1 authentication.  I'm not sure what the solution to all this will be, but I have a feeling the mongoose api will be different.

**Comment by johnstonbl01** [comment]
Have you tried using MongoLab and connecting via a URI instead of using the Heroku add-on?

**Comment by TheHexorcist** [comment]
The only way to use MongoDB on heroku is through the heroku add-on.  Its not an option as far as I know.  I've tried the URI method and mongo shell to access with no success.  It could be something else but authentication seems to be the only problem.  I'm able to login with mongo shell using no user or password but I can't do anything with the db.

interesting link here http://docs.mongolab.com/db-version-requirements/

**Comment by johnstonbl01** [comment]
That's not true. If you setup a MongoLab account, and give your database a username and password -- you can connect to that instance via the URI. Have you setup a username and password for the db? 

Can you show me the actual error message you're receiving? I have not had any issues with Heroku and Mongo 3.0 with Mongoose. Clementine was developed on Mongo 3.0.

**Comment by johnstonbl01** [comment]
Also - try these steps:
1. Setup a Clementinejs clone on c9.io. Confirm that it works as expected.
2. Sign up for an account on Heroku.
3. Sign up for an account on MongoLab
4. In the c9.io terminal: 
   - `heroku create`. Enter Heroku credentials when prompted
   - `git push heroku master`. Note the name of the randomly created URL that Heroku provides. fathomless-retreat-4813 in my case. The app's URL will be: https://fathomless-retreat-4813.herokuapp.com/
5. Go to GitHub and set up a new development application to get a new set of API keys. This is required since the callback and application URLs will be different than the dev environment on c9.
6. Return to the MongoLab website.
   - Once logged in, under MongoDB Deployments, click the 'Create new' button
   - Choose Single-node
   - Choose 'Sandbox' -- the free option
   - For database name, enter a name for the db. I used 'clementinejs'.
   - Click 'Create new MongoDB deployment'
   - Once that's done, click on the new database from the MongoLab dashboard.
   - Click the 'Users' tab.
   - Click 'Add database user'
     - Create a database username and password. This is required. I used something easy to remember.
   - Once this is done, at the top you'll see the MongoLab URI for this new database. It will look something like `mongodb://<dbuser>:<dbpassword>@ds999999.mongolab.com:99999/clemenintejs`. Leave this tab open.
7. Return to Heroku.com
   - You should now see your newly deployed app at the bottom of the screen. Click on it.
   - At the top, go to Settings.
     - Click Reveal Config Vars
     - Create the following configuration variables:
       - GITHUB_KEY: your-client-key-here
       - GITHUB_SECRET: your-client-secret-here
       - APP_URL: your-app-url (mine was https://fathomless-retreat-4813.herokuapp.com/). Make sure there is a forward slash (`/`) at the end of this url.
       - MONGO_URI: the URI from MongoLab
         - Change `<dbuser>` and `<dbpassword>` to be the username and password setup for the database. The brackets surrounding the values are not needed. (For example: `mongodb://blakej:password@ds999999.mongolab.com:99999/clemenintejs`)
       - A PORT variable is **NOT** needed. Heroku takes care of this behind the scenes.
8. Open a browser and point it to the app URL: https://fathomless-retreat-4813.herokuapp.com/
   - This is deployed and working if you want to test it.

**Comment by TheHexorcist** [comment]
Your setup is identically to how I did mine.  The thing that stands out to me is the 2.6.11 but the mongolab is running 3.0.7.  Keep in mind I can login without user name and password just fine.

`MongoDB shell version: 2.6.11
connecting to: ds057954.mongolab.com:57954/heroku_v1nd35x2
2015-11-27T22:08:32.946+0000 Error: 18 { ok: 0.0, errmsg: "auth failed", code: 18 } at src/mongo/shell/db.js:1292
exception: login failed`

here is a login without authentication

`MongoDB shell version: 2.6.11
connecting to: ds057954.mongolab.com:57954/heroku_v1nd35x2
rs-ds057954:PRIMARY>`

**Comment by johnstonbl01** [comment]
I couldn't get MongoLab to work **without** setting up a username and password _for the database_. I just spun up my Heroku app without any changes to the FCC Clementine application. It works fine.

Please try the steps posted above and let me know:
1. On which step you run into an issue.
2. A screenshot or snippet of the error message.
3. Are you developing in a local environment or on c9?

**Comment by HexORSist** [comment]
`2015-11-27T23:38:28.633343+00:00 heroku[web.1]: State changed from starting to crashed
2015-11-27T23:38:28.634671+00:00 heroku[web.1]: State changed from crashed to starting
2015-11-27T23:38:28.621251+00:00 heroku[web.1]: Process exited with status 1
2015-11-27T23:38:29.791689+00:00 heroku[web.1]: Starting process with command `npm start`
2015-11-27T23:38:31.949385+00:00 app[web.1]: 
2015-11-27T23:38:31.949396+00:00 app[web.1]: > clementinejs-fcc@1.0.1 start /app
2015-11-27T23:38:31.949398+00:00 app[web.1]: > node server.js
2015-11-27T23:38:31.949399+00:00 app[web.1]: 
2015-11-27T23:38:32.531429+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2015-11-27T23:38:32.531432+00:00 app[web.1]: designed for a production environment, as it will leak
2015-11-27T23:38:32.531434+00:00 app[web.1]: memory, and will not scale past a single process.
2015-11-27T23:38:32.549807+00:00 app[web.1]: Node.js listening on port 17809...
2015-11-27T23:38:32.586676+00:00 app[web.1]: npm ERR! Linux 3.13.0-66-generic
2015-11-27T23:38:32.586988+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-11-27T23:38:32.587147+00:00 app[web.1]: npm ERR! node v5.0.0
2015-11-27T23:38:32.587551+00:00 app[web.1]: npm ERR! npm  v3.3.6
2015-11-27T23:38:32.588339+00:00 app[web.1]: npm ERR! Exit status 1
2015-11-27T23:38:32.587704+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-11-27T23:38:32.588696+00:00 app[web.1]: npm ERR! This is most likely a problem with the clementinejs-fcc package,
2015-11-27T23:38:32.588915+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-11-27T23:38:32.588101+00:00 app[web.1]: npm ERR! clementinejs-fcc@1.0.1 start: `node server.js`
2015-11-27T23:38:32.588474+00:00 app[web.1]: npm ERR! 
2015-11-27T23:38:32.588583+00:00 app[web.1]: npm ERR! Failed at the clementinejs-fcc@1.0.1 start script 'node server.js'.
2015-11-27T23:38:32.588813+00:00 app[web.1]: npm ERR! not with npm itself.
2015-11-27T23:38:32.589228+00:00 app[web.1]: npm ERR!     npm owner ls clementinejs-fcc
2015-11-27T23:38:32.589021+00:00 app[web.1]: npm ERR!     node server.js
2015-11-27T23:38:32.589128+00:00 app[web.1]: npm ERR! You can get their info via:
2015-11-27T23:38:32.592418+00:00 app[web.1]: 
2015-11-27T23:38:32.589335+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-11-27T23:38:32.592701+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-11-27T23:38:32.592893+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-11-27T23:38:32.492510+00:00 app[web.1]: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2015-11-27T23:38:32.572117+00:00 app[web.1]: 
2015-11-27T23:38:32.572121+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:235
2015-11-27T23:38:32.572123+00:00 app[web.1]:                                       ^
2015-11-27T23:38:32.572122+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-11-27T23:38:32.572126+00:00 app[web.1]: Error: getaddrinfo ENOTFOUND undefined undefined:27017
2015-11-27T23:38:32.572127+00:00 app[web.1]:     at errnoException (dns.js:26:10)
2015-11-27T23:38:32.582354+00:00 app[web.1]: 
2015-11-27T23:38:32.572128+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
2015-11-27T23:38:33.286500+00:00 heroku[web.1]: Process exited with status 1
2015-11-27T23:38:33.278156+00:00 heroku[web.1]: State changed from starting to crashed`

**Comment by johnstonbl01** [comment]
I just re-cloned the repo in c9, setup a new Heroku app using the steps I outlined above and didn't have a single issue. I don't think this is a problem with Clementine.

Did you try cloning your project to a new workspace in c9 and following the steps I provided? If so, please provide a link to your c9 workspace and I can take a look. If not, please do that first.

**Comment by TheHexorcist** [comment]
could you look at the version your running on mongolab?  you can see this in the link https://www.mongolab.com/databases/heroku_8hf6p4w7 the only difference is the path at the end of the URL is your database name.  You should see a rectangular box and in that box at the lower right is a version number.  Mine says mongod version: 3.0.7

**Comment by johnstonbl01** [comment]
3.0.7

As mentioned previously, Clementine was developed on Mongo 3.0+ -- there is no conflict between the Mongo version and the application whatsoever. There is an issue with something that has changed since you've cloned the project from the repo.

![mongolab_version](https://cloud.githubusercontent.com/assets/1808501/11452368/f563d590-95aa-11e5-8749-5d176994563f.png)

**Comment by TheHexorcist** [comment]
I'm not sure whats going on here.  I re-cloned and started completely over with the same log errors. There is something that is slightly different in how you describe the setup.  mongolab does the automatic setup of the database including the "MONGOLAB_URI" key.  Is the default URI setup faulty using this "MONGOLAB_URI"?

**Comment by johnstonbl01** [comment]
Yes. MongoLab does not setup a username and password for the db. You must do that manually. Did you do that?

**Comment by TheHexorcist** [comment]
mongolab automatically setup a username and password for me when I provisioned mongolab for the app. There is no manual process?

**Comment by johnstonbl01** [comment]
Are you still just using the Heroku add-on or setting it up on the MongoLab website like I suggest? If you're using the web site, it does not automatically set up a username and password. 

After creating the db, you have to click on it and there is a tab at the top to create a user and password. This is explicitly mentioned in the steps above.

**Comment by TheHexorcist** [comment]
I'm still using the heroku add-on.  I thought you had to have the mongolab add-on for moongose to make its connection?  Is this not the case?

**Comment by johnstonbl01** [comment]
No - the Heroku add on isn't required. Use the MongoLab web site - it's
more robust and clear. Then you copy and paste the URI into the Heroku
environment settings (after changing the username / password). Try the
steps I outlined -- they work.

**Comment by HexORSist** [comment]
I received a response from mongolab support 

`Hi,

Sorry to hear that you are having trouble connecting.

We're seeing the following error in this deployment's database log (timestamps are in Pacific Time):

2015-11-28T06:52:38.911-0800 I ACCESS   [conn338415]  authenticate db: heroku_v6lwgxp8 { authenticate: 1, nonce: "xxx", user: "heroku_v6lwgxp8", key: "xxx" }
2015-11-28T06:52:38.912-0800 I ACCESS   [conn338415] Failed to authenticate heroku_v6lwgxp8@heroku_v6lwgxp8 with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document
2015-11-28T06:55:35.551-0800 I ACCESS   [conn338678]  authenticate db: heroku_v6lwgxp8 { authenticate: 1, nonce: "xxx", user: "hexorsist", key: "xxx" }
2015-11-28T06:55:35.552-0800 I ACCESS   [conn338678] Failed to authenticate hexorsist@heroku_v6lwgxp8 with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document

This indicates that either the shell and/or driver you are connecting with is not compatible with MongoDB 3.0.x, the version that this database is running. If you haven't already, could you look at the following troubleshooting documentation?

http://docs.mongolab.com/connecting/#version-compatibility

If you continue to experience issues after following the troubleshooting guide or have any follow-up questions, please let us know.'

**Comment by HexORSist** [comment]
FYI

https://github.com/Automattic/mongoose/issues/3621

**Comment by TheHexorcist** [comment]
I figured out the problem mongolab generates a "MONGOLAB_URI" key and in the server.js file it is "MONGO_URI" key.  I apologize for the confusion.  You might consider adding this to the setup so other FCC users dont fall into the trap I did.

**Comment by dbender** [comment]
I tried following the steps you gave TheHexorcist last November, and something went wrong on step 4 when I gave the "heroku create" command. Below is the contents of my /home/ubuntu/.heroku/error.log file. What do I need to fix?

2016/03/16 04:12:13 heroku-cli: Adding dependencies...
2016/03/16 04:12:16  done
2016/03/16 04:12:16 truncating error log...
2016/03/16 04:12:16 cleaning up tmp dirs...
2016/03/16 04:12:16 heroku-cli: Installing core plugins...
2016/03/16 04:12:29  done
2016/04/01 15:59:48 Email: 
2016/04/01 15:59:48 heroku-cli: Updating to 4.28.3-144406a... 
2016/04/01 15:59:49 done
2016/04/01 15:59:49 reexecing new CLI...
2016/04/01 15:59:55 heroku-cli: Updating plugins... 
2016/04/01 16:00:06 ERROR: fork/exec /home/ubuntu/.heroku/node-v5.7.1-linux-x64/bin/node: no such file or directory
2016/04/01 16:00:09 
2016/04/01 16:00:09  ▸    Error reading plugin: heroku-local
 ▸    exit status 1
2016/04/01 16:00:13 
2016/04/01 16:00:13  ▸    Error installing package. 
 ▸    npm WARN ENOENT ENOENT: no such file or directory, open '/home/ubuntu/.heroku/package.json'
 ▸    npm WARN EPACKAGEJSON .heroku No description
 ▸    npm WARN EPACKAGEJSON .heroku No repository field.
 ▸    npm WARN EPACKAGEJSON .heroku No README data
 ▸    npm WARN EPACKAGEJSON .heroku No license field.
 ▸    npm ERR! Linux 4.2.0-c9
 ▸    npm ERR! argv "/home/ubuntu/.heroku/node-v5.9.1-linux-x64/bin/node" "/home/ubuntu/.heroku/node-v5.9.1-linux-x64/lib/node_modules/npm/cli.js" "install" "heroku-orgs@1.0.5"
 ▸    npm ERR! node v5.9.1
 ▸    npm ERR! npm  v3.3.10
 ▸    npm ERR! path /home/ubuntu/.heroku/node_modules/heroku-orgs
 ▸    npm ERR! code EXDEV
 ▸    npm ERR! errno -18
 ▸    npm ERR! syscall rename
 ▸    
 ▸    npm ERR! EXDEV: cross-device link not permitted, rename '/home/ubuntu/.heroku/node_modules/heroku-orgs' -> '/home/ubuntu/.heroku/node_modules/.heroku-orgs.DELETE'
 ▸    npm ERR! 
 ▸    npm ERR! If you need help, you may report this error at:
 ▸    npm ERR!     <https://github.com/npm/npm/issues>
 ▸    
 ▸    npm ERR! Please include the following file with any support request:
 ▸    npm ERR!     /home/ubuntu/.heroku/npm-debug.log
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
2016/04/01 16:00:13 
2016/04/01 16:00:13  ▸    Error reading plugin: heroku-orgs
 ▸    exit status 1
2016/04/01 16:00:18 
2016/04/01 16:00:18  ▸    Error installing package. 
 ▸    npm WARN install:lodash@4.6.1 EXDEV: cross-device link not permitted, rename '/home/ubuntu/.heroku/node_modules/heroku-run/node_modules/lodash' -> '/home/ubuntu/.heroku/node_modules/heroku-run/node_modules/.lodash.DELETE'
 ▸    npm WARN ENOENT ENOENT: no such file or directory, open '/home/ubuntu/.heroku/package.json'
 ▸    npm WARN EPACKAGEJSON .heroku No description
 ▸    npm WARN EPACKAGEJSON .heroku No repository field.
 ▸    npm WARN EPACKAGEJSON .heroku No README data
 ▸    npm WARN EPACKAGEJSON .heroku No license field.
 ▸    npm ERR! code 1
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
2016/04/01 16:00:20 heroku-cli: Installing core plugins...
2016/04/01 16:00:24 
2016/04/01 16:00:24  ▸    Error installing package. 
 ▸    npm WARN ENOENT ENOENT: no such file or directory, open '/home/ubuntu/.heroku/package.json'
 ▸    npm WARN EPACKAGEJSON .heroku No description
 ▸    npm WARN EPACKAGEJSON .heroku No repository field.
 ▸    npm WARN EPACKAGEJSON .heroku No README data
 ▸    npm WARN EPACKAGEJSON .heroku No license field.
 ▸    npm ERR! Linux 4.2.0-c9
 ▸    npm ERR! argv "/home/ubuntu/.heroku/node-v5.9.1-linux-x64/bin/node" "/home/ubuntu/.heroku/node-v5.9.1-linux-x64/lib/node_modules/npm/cli.js" "install" "heroku-spaces@2.1.2"
 ▸    npm ERR! node v5.9.1
 ▸    npm ERR! npm  v3.3.10
 ▸    npm ERR! path /home/ubuntu/.heroku/node_modules/heroku-spaces
 ▸    npm ERR! code EXDEV
 ▸    npm ERR! errno -18
 ▸    npm ERR! syscall rename
 ▸    
 ▸    npm ERR! EXDEV: cross-device link not permitted, rename '/home/ubuntu/.heroku/node_modules/heroku-spaces' -> '/home/ubuntu/.heroku/node_modules/.heroku-spaces.DELETE'
 ▸    npm ERR! 
 ▸    npm ERR! If you need help, you may report this error at:
 ▸    npm ERR!     <https://github.com/npm/npm/issues>
 ▸    
 ▸    npm ERR! Please include the following file with any support request:
 ▸    npm ERR!     /home/ubuntu/.heroku/npm-debug.log
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
2016/04/01 16:00:25 
2016/04/01 16:00:25  ▸    Error reading plugin: heroku-spaces
 ▸    exit status 1
2016/04/01 16:00:28 
2016/04/01 16:00:28  ▸    exit status 217
2016/04/01 16:00:28 heroku-cli: Installing core plugins (retrying)...
2016/04/01 16:00:35 
2016/04/01 16:00:35  ▸    Error reading plugin: heroku-orgs
 ▸    exit status 1
2016/04/01 16:00:35 heroku-cli: Installing core plugins...
2016/04/01 16:00:36 
2016/04/01 16:00:36  ▸    Error reading plugin: heroku-status
 ▸    exit status 1
2016/04/01 16:00:44  done
2016/04/01 16:00:47 
2016/04/01 16:00:47  ▸    Error reading plugin: heroku-apps
 ▸    exit status 1
2016/04/01 16:00:48 Error during create:null
2016/04/01 16:00:48 Error: Cannot find module 'filesize'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ubuntu/.heroku/node_modules/heroku-apps/commands/apps/info.js:8:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
2016/04/01 16:00:52 
2016/04/01 16:00:52  ▸    Error installing package. 
 ▸    npm WARN ENOENT ENOENT: no such file or directory, open '/home/ubuntu/.heroku/package.json'
 ▸    npm WARN EPACKAGEJSON .heroku No description
 ▸    npm WARN EPACKAGEJSON .heroku No repository field.
 ▸    npm WARN EPACKAGEJSON .heroku No README data
 ▸    npm WARN EPACKAGEJSON .heroku No license field.
 ▸    npm ERR! Linux 4.2.0-c9
 ▸    npm ERR! argv "/home/ubuntu/.heroku/node-v5.9.1-linux-x64/bin/node" "/home/ubuntu/.heroku/node-v5.9.1-linux-x64/lib/node_modules/npm/cli.js" "install" "heroku-cli-addons@0.3.0"
 ▸    npm ERR! node v5.9.1
 ▸    npm ERR! npm  v3.3.10
 ▸    npm ERR! path /home/ubuntu/.heroku/node_modules/heroku-cli-addons
 ▸    npm ERR! code EXDEV
 ▸    npm ERR! errno -18
 ▸    npm ERR! syscall rename
 ▸    
 ▸    npm ERR! EXDEV: cross-device link not permitted, rename '/home/ubuntu/.heroku/node_modules/heroku-cli-addons' -> '/home/ubuntu/.heroku/node_modules/.heroku-cli-addons.DELETE'
 ▸    npm ERR! 
 ▸    npm ERR! If you need help, you may report this error at:
 ▸    npm ERR!     <https://github.com/npm/npm/issues>
 ▸    
 ▸    npm ERR! Please include the following file with any support request:
 ▸    npm ERR!     /home/ubuntu/.heroku/npm-debug.log
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
2016/04/01 16:00:52 
2016/04/01 16:00:52  ▸    Error reading plugin: heroku-cli-addons
 ▸    exit status 1
2016/04/01 16:00:52 done. Updated 7 packages.
2016/04/01 16:00:52 truncating error log...
2016/04/01 16:00:52 cleaning up tmp dirs...
2016/04/01 16:00:52 heroku-cli: Installing core plugins...
2016/04/01 16:00:56  done

**Comment by dbender** [comment]
Disregard previous question. I deleted the entire .heroku directory tree and ran heroku create again, this time successfully.
